#!/usr/bin/bash

############################### FOLDER ICONS ###################################

SESSION="learning"

# Attach to Tmux

tmux bind c new-window -c "#{pane_current_path}"
if [ -z "$TMUX" ]; then
    # We're not inside Tmux
    echo "Attaching to $SESSION"
    # tmux -t "$SESSION" bind c new-window -c $1
    tmux attach-session -d -t "$SESSION" || tmux new-session -s "$SESSION"
     # -L vscode
else
    # We're inside Tmux
    if [ -z "$(tmux ls | grep $SESSION)" ]; then
        # Create a new dettached session
        tmux new -s "$SESSION" -d
        # -L vscode
    fi

    # attach rather that switch - uses vscode terminal rather than external terminal
    tmux attach-session -d -t "$SESSION" || tmux new-session -s "$SESSION"

    # # Switch to the session
    # tmux switch-client -t "$SESSION"
    # # -L vscode
fi
