#!/usr/bin/env python3
"""audio and video metadata writer"""
import argparse
import pprint

import pydub

# import audio_metadata as am

ap = argparse.ArgumentParser()
ap.add_argument("input", help="path to the input file")
args = ap.parse_args()

pp = pprint.PrettyPrinter()
# test_file = "e:/audio_files/test/test.mp4"
# print(args)
test_file = args.input

py_meta = pydub.utils.mediainfo(test_file)
# metadata = am.load(test_file)

pp.pprint(py_meta)
# print("\n\n")
# pp.pprint(metadata)
