#!/bin/bash

############################### FOLDER ICONS ###################################

folder="$(pwd)"

# Construct the path for the folder icon
FOLDER_ICON_PATH="$folder/.icon"

# Strip the path and leave the folder name
folder_name="$(basename $folder)"

if [ -f $FOLDER_ICON_PATH ]; then
    folder_icon="$(cat $FOLDER_ICON_PATH)"

    # Construct the session name
    SESSION="$folder_name $folder_icon"
else
    echo "Could not find an .icon file in $folder, using no icon"
    folder_icon="🖥️"

    SESSION="$folder_name"
fi


# Attach to Tmux

tmux bind c new-window -c "#{pane_current_path}"
if [ -z "$TMUX" ]; then
    # We're not inside Tmux
    echo "Attaching to $SESSION"
    # tmux -t "$SESSION" bind c new-window -c $1
    tmux attach-session -d -t "$SESSION" || tmux new-session -s "$SESSION"
     # -L vscode
else
    # We're inside Tmux
    if [ -z "$(tmux ls | grep $SESSION)" ]; then
        # Create a new dettached session
        tmux new -s "$SESSION" -d
        # -L vscode
    fi

    # attach rather that switch - uses vscode terminal rather than external terminal
    tmux attach-session -d -t "$SESSION" || tmux new-session -s "$SESSION"

    # # Switch to the session
    # tmux switch-client -t "$SESSION"
    # # -L vscode
fi
